Repository monal-im/Monal, pull requests merged in 2020-12, with the labels that each got.

#517 Pr09.2 fix1 (OMEMO, filtransfer, logs)
  Monal/Classes/DataLayer.m
  Monal/Classes/MLConstants.h
  Monal/Classes/MLDNSLookup.m
  Monal/Classes/MLFiletransfer.h
  Monal/Classes/MLFiletransfer.m
  Monal/Classes/MLNotificationManager.m
  Monal/Classes/MLOMEMO.m
  Monal/Classes/MLPubSub.m
  Monal/Classes/MonalAppDelegate.m
  Monal/Classes/chatViewController.m
  Monal/Classes/xmpp.m
  Monal/NotificaionService/NotificationService.m
  Monal/localization/Base.lproj/Localizable.strings
  Monal/localization/ar.lproj/Localizable.strings
  Monal/localization/cs.lproj/Localizable.strings
  Monal/localization/da.lproj/Localizable.strings
  Monal/localization/de.lproj/Localizable.strings
  Monal/localization/de.lproj/Settings.strings
  Monal/localization/el.lproj/Localizable.strings
  Monal/localization/es-419.lproj/Localizable.strings
  Monal/localization/es.lproj/Localizable.strings
  Monal/localization/fa.lproj/Localizable.strings
  Monal/localization/fi.lproj/Localizable.strings
  Monal/localization/fr.lproj/Localizable.strings
  Monal/localization/fr.lproj/Settings.strings
  Monal/localization/he.lproj/Localizable.strings
  Monal/localization/hi.lproj/Localizable.strings
  Monal/localization/it.lproj/Localizable.strings
  Monal/localization/ja.lproj/Localizable.strings
  Monal/localization/nb-NO.lproj/Localizable.strings
  Monal/localization/ne.lproj/Localizable.strings
  Monal/localization/nl.lproj/Localizable.strings
  Monal/localization/pl.lproj/Localizable.strings
  Monal/localization/ro.lproj/Localizable.strings
  Monal/localization/ru.lproj/Localizable.strings
  Monal/localization/sv.lproj/Localizable.strings
  Monal/localization/tr.lproj/Localizable.strings
  Monal/localization/uk.lproj/Localizable.strings
  Monal/localization/vi.lproj/Localizable.strings
  Monal/localization/zh-Hant-HK.lproj/Localizable.strings
  Monal/localization/zh-Hant.lproj/Localizable.strings
Labels: :fish: OMEMO, :no_entry_sign: Bug / Stability, :speech_balloon: Translation

#522 Pr09.2 fix3 - Fix NSE handling, avatar refresh
  Monal/Classes/DataLayer.m
  Monal/Classes/MLBackgroundSettings.m
  Monal/Classes/MLFiletransfer.m
  Monal/Classes/MLHTTPRequest.m
  Monal/Classes/MLImageManager.m
  Monal/Classes/MLProcessLock.m
  Monal/Classes/MLPubSubProcessor.m
  Monal/Classes/MLSignalStore.m
  Monal/Classes/MLXMLNode.m
  Monal/NotificaionService/NotificationService.m
Labels: :art: UI, :no_entry_sign: Bug / Stability

#524 PR09.2 - Fix4 - OMEMO PreKey Cache
  Monal/Classes/MLOMEMO.m
  Monal/Classes/MLSignalStore.m
Labels: :fish: OMEMO, :no_entry_sign: Bug / Stability

#529 Fix edit swipe action to stop editing on send
  Monal/Classes/chatViewController.m
Labels: :art: UI, :no_entry_sign: Bug / Stability

#530 Pr09.2 fix6
  Monal/Classes/DataLayer.m
Labels: :no_entry_sign: Bug / Stability

#531 Pr09.2 fix7 - Romanian translation
  Monal/localization/ro.lproj/Localizable.strings
  Monal/localization/ro.lproj/Login.strings
  Monal/localization/ro.lproj/Main.strings
  Monal/localization/ro.lproj/Settings.strings
Labels: :speech_balloon: Translation

#534 Fix sending opportunistic smacks ack too early
  Monal/Classes/xmpp.m
Labels: :no_entry_sign: Bug / Stability
