Repository monal-im/Monal, pull requests merged in 2020-08, with the labels that each got.

#436 Fix typo
  Monal/Classes/MLSubscriptionTableViewController.m
Labels: :no_entry_sign: Bug / Stability, :speech_balloon: Translation

#439 Update custom.md
  .github/ISSUE_TEMPLATE/custom.md
Labels: :superhero: Help wanted

#445 Add newest Localizable.strings
  Monal/Base.lproj/Localizable.strings
Labels: :speech_balloon: Translation

#446 Rename folder for strings
  Monal/en.lproj/Localizable.strings
Labels: :speech_balloon: Translation

#448 Revert "Rename folder for strings"
  Monal/en.lproj/Localizable.strings
Labels: :speech_balloon: Translation

#450 Fix typo in english message
  Monal/Base.lproj/Localizable.strings
  Monal/Classes/ActiveChatsViewController.m
Labels: :speech_balloon: Translation

#449 Translations update from Weblate
  Monal/ar.lproj/Localizable.strings
  Monal/de.lproj/Localizable.strings
  Monal/es-419.lproj/Localizable.strings
  Monal/es.lproj/Localizable.strings
  Monal/fr.lproj/Localizable.strings
  Monal/he.lproj/Localizable.strings
  Monal/hi.lproj/Localizable.strings
  Monal/it.lproj/Localizable.strings
  Monal/nl.lproj/Localizable.strings
  Monal/pl.lproj/Localizable.strings
  Monal/pt.lproj/Localizable.strings
  Monal/ro.lproj/Localizable.strings
  Monal/ru.lproj/Localizable.strings
  Monal/sv.lproj/Localizable.strings
  Monal/uk.lproj/Localizable.strings
  Monal/vi.lproj/Localizable.strings
Labels: :speech_balloon: Translation

#451 Translations update from Weblate
  Monal/de.lproj/Localizable.strings
  Monal/es.lproj/Localizable.strings
  Monal/fr.lproj/Localizable.strings
  Monal/nl.lproj/Localizable.strings
  Monal/ro.lproj/Localizable.strings
  Monal/zh-Hant-HK.lproj/Localizable.strings
  Monal/zh-Hant.lproj/Localizable.strings
Labels: :speech_balloon: Translation

#452 Update ReadMe.md
  ReadMe.md
Labels: :superhero: Help wanted

#460 Translations update from Weblate
  Monal/de.lproj/ContactDetails.strings
  Monal/de.lproj/Login.strings
  Monal/de.lproj/Main.strings
  Monal/de.lproj/Settings.strings
  Monal/ro.lproj/ContactDetails.strings
  Monal/ro.lproj/Login.strings
  Monal/ro.lproj/Main.strings
  Monal/ro.lproj/Settings.strings
  Monal/shareSheet-iOS/de.lproj/iosShare.strings
  Monal/shareSheet-iOS/ro.lproj/iosShare.strings
Labels: :speech_balloon: Translation

#466 List known server software by popularity
  Monal/Base.lproj/Localizable.strings
Labels: :art: UI

#433 Update XEPsupport.md
  XEPsupport.md
Labels: :bookmark_tabs: XEP

#476 fix weblate
  Monal/Monal.xcodeproj/project.pbxproj
  Monal/localization/zh-HK.lproj/ContactDetails.strings
  Monal/localization/zh-HK.lproj/Login.strings
  Monal/localization/zh-HK.lproj/Main.strings
  Monal/localization/zh-HK.lproj/Settings.strings
  Monal/localization/zh-Hant.lproj/Localizable.strings
Labels: :no_entry_sign: Bug / Stability, :speech_balloon: Translation
