Repository monal-im/Monal, pull requests merged in 2020-03, with the labels that each got.

#366 Some more fixes
  Monal/Classes/MLXMPPManager.m
  Monal/Classes/ParseMessage.h
  Monal/Classes/ParseMessage.m
  Monal/Classes/xmpp.m
Labels: Bug / Stability, Catalyst, MUC, iOS

#381 Fixing roster updates
  Monal/Classes/MLIQProcessor.m
Labels: Bug / Stability, Feature

#382 Basic message draft support
  Monal/Classes/DataLayer.h
  Monal/Classes/DataLayer.m
  Monal/Classes/chatViewController.m
Labels: Feature, UI
