Repository monal-im/Monal, pull requests merged in 2020-10, with the labels that each got.

#489 Pr08 fix03
  Monal/Classes/DataLayer.m
  Monal/Classes/IPC.h
  Monal/Classes/IPC.m
  Monal/Classes/MLProcessLock.m
  Monal/Classes/MLXMPPManager.m
  Monal/Classes/xmpp.m
Labels: :no_entry_sign: Bug / Stability

#487 Update XEPsupport.md
  XEPsupport.md
Labels: :bookmark_tabs: XEP, :superhero: Help wanted

#490 Update custom.md
  .github/ISSUE_TEMPLATE/custom.md
Labels: :superhero: Help wanted, Minor

#493 Update ReadMe.md
  ReadMe.md
Labels: :superhero: Help wanted
