Repository monal-im/Monal, pull requests merged in 2020-04, with the labels that each got.

#388 Fix change password #370
  Monal/Classes/xmpp.m
Labels: Bug / Stability

#390 display geo location
  Monal/Classes/ActiveChatsViewController.m
  Monal/Classes/DataLayer.h
  Monal/Classes/DataLayer.m
  Monal/Classes/MLChatMapsCell.h
  Monal/Classes/MLChatMapsCell.m
  Monal/Classes/MLDisplaySettingsViewController.m
  Monal/Classes/MLNotificationManager.m
  Monal/Classes/MLXMPPManager.m
  Monal/Classes/Main.storyboard
  Monal/Classes/chatViewController.m
  Monal/Monal.xcodeproj/project.pbxproj
Labels: Feature, UI

#330 Update issue templates
  .github/ISSUE_TEMPLATE/custom-template.md
  .github/ISSUE_TEMPLATE/custom.md
Labels: Feature, Help wanted

#386 Show messageDrafts in ActiveChatsViewController
  Monal/Classes/ActiveChatsViewController.m
  Monal/Classes/DataLayer.h
  Monal/Classes/DataLayer.m
  Monal/Classes/MLAttributedLabel.h
  Monal/Classes/MLAttributedLabel.m
  Monal/Classes/MLContactCell.h
  Monal/Classes/MLContactCell.m
  Monal/Classes/MLContactCell.xib
  Monal/Classes/chatViewController.m
  Monal/Monal.xcodeproj/project.pbxproj
Labels: Feature, UI

#385 Fix #206 (Implement SRV lookup)
  Monal/Classes/DataLayer.m
  Monal/Classes/MLDNSLookup.m
  Monal/Classes/MLRegisterViewController.m
  Monal/Classes/MLXMPPManager.m
  Monal/Classes/MLXMPPServer.h
  Monal/Classes/MLXMPPServer.m
  Monal/Classes/xmpp.h
  Monal/Classes/xmpp.m
  Monal/Monal Tests/XMPP Tests/MLIQParserTest.m
  Monal/Monal Tests/XMPP Tests/MLIQProcessorTest.m
  Monal/Monal Tests/XMPP Tests/MLMessageParserTest.m
  Monal/Monal Tests/XMPP Tests/MLMessageProcessorTest.m
Labels: Bug / Stability

#395 Add debug attributes to smacks requests
  Monal/Classes/ContactDetails.m
  Monal/Classes/DataLayer.h
  Monal/Classes/DataLayer.m
  Monal/Classes/MLIQProcessor.h
  Monal/Classes/MLIQProcessor.m
  Monal/Classes/MLKeysTableViewController.m
  Monal/Classes/MLMessageProcessor.h
  Monal/Classes/MLMessageProcessor.m
  Monal/Classes/MLXMPPManager.m
  Monal/Classes/chatViewController.m
  Monal/Classes/xmpp.m
  Monal/Monal Tests/XMPP Tests/MLIQProcessorTest.m
Labels: :no_entry_sign: Bug / Stability

#393 Refactored table account
  Monal/Classes/ContactsViewController.m
  Monal/Classes/DataLayer.h
  Monal/Classes/DataLayer.m
  Monal/Classes/MLXMPPManager.m
  Monal/Classes/xmpp.m
Labels: :bookmark_tabs: XEP, :no_entry_sign: Bug / Stability

#394 Adding send geo location button
  Monal/Classes/Main.storyboard
  Monal/Classes/chatViewController.h
  Monal/Classes/chatViewController.m
  Monal/Monal-Info.plist
  Monal/Monal.xcodeproj/project.pbxproj
Labels: :art: UI, :tada: Feature

#396 Allow overriding host and port in advanced settings, fixes #242
  Monal/Classes/DataLayer.m
  Monal/Classes/MLIQProcessor.m
  Monal/Classes/MLLogInViewController.m
  Monal/Classes/MLMAMPrefTableViewController.m
  Monal/Classes/MLRegisterViewController.m
  Monal/Classes/MLServerDetails.m
  Monal/Classes/MLXMPPManager.m
  Monal/Classes/XMPPEdit.m
  Monal/Classes/xmpp.m
Labels: :no_entry_sign: Bug / Stability

#397 Update licence.txt
  licence.txt
Labels: :grey_question: Question

#398 Fix connecting to servers without SRV records and display a warning for "." SRV records, fix some dns resolver problems
  Monal/Classes/DataLayer.m
  Monal/Classes/MLDNSLookup.h
  Monal/Classes/MLDNSLookup.m
  Monal/Classes/MLXMPPManager.m
  Monal/Classes/XMPPIQ.m
  Monal/Classes/chatViewController.m
  Monal/Classes/xmpp.m
Labels: :bookmark_tabs: XEP, :no_entry_sign: Bug / Stability
