Repository monal-im/Monal, pull requests merged in 2021-02, with the labels that each got.

#500 Create AppStoreDescription
  AppStoreDescrition
Labels: :speech_balloon: Translation, :superhero: Help wanted

#501 Create monal.doap
  XEPsupport.md
  monal.doap
Labels: :bookmark_tabs: XEP, :superhero: Help wanted

#555 UI adjust, bump version, fix constraints, update podfile
  Monal/Classes/MLConstants.h
  Monal/Classes/chatViewController.m
  Monal/Monal-Info.plist
  Monal/Monal.xcodeproj/project.pbxproj
  Monal/Podfile.lock
  Monal/localization/Base.lproj/Main.storyboard
Labels: :art: UI, :no_entry_sign: Bug / Stability

#560 Update and rename AppStoreDescrition to AppStoreDescrition.md
  AppStoreDescription.md
Labels: Minor

#556 Travis builds
  Monal/Monal Tests/XMPP Tests/MLIQParserTest.m
  Monal/Monal Tests/XMPP Tests/MLIQProcessorTest.m
  Monal/Monal Tests/XMPP Tests/MLMessageParserTest.m
  Monal/Monal Tests/XMPP Tests/MLMessageProcessorTest.m
Labels: :art: UI, :no_entry_sign: Bug / Stability

#562 Reset bubble and font size for all cells
  Monal/Classes/chatViewController.m
Labels: :art: UI

#567 Patch 4.9.2
  Monal/Classes/HelperTools.h
  Monal/Classes/HelperTools.m
  Monal/Classes/MLIQProcessor.m
  Monal/Classes/MLLogInViewController.m
  Monal/Classes/MLMessageProcessor.m
  Monal/Classes/MLOMEMO.m
  Monal/Classes/MLRegSuccessViewController.m
  Monal/Classes/MLRegisterViewController.m
  Monal/Classes/MLXMLNode.m
  Monal/Classes/MLXMPPManager.m
  Monal/Classes/MonalAppDelegate.m
  Monal/Classes/xmpp.m
  Monal/Monal.xcodeproj/project.pbxproj
  Monal/NotificaionService/NotificationService.m
  Monal/Podfile
  Monal/Podfile.lock
  Monal/localization/Base.lproj/Login.storyboard
Labels: :no_entry_sign: Bug / Stability

#568 support both import paths that pycryptodome might use
  UDPLogServer/server.py
Labels: :grey_question: Question, :no_entry_sign: Bug / Stability

#561 Update custom.md
  .github/ISSUE_TEMPLATE/custom.md
Labels: Minor

#557 Update status and remove version
  monal.doap
Labels: :bookmark_tabs: XEP, :superhero: Help wanted, Minor

#578 Audio player
  Monal/Classes/chatViewController.m
  Monal/localization/Base.lproj/Main.storyboard
Labels: :art: UI, :tada: Feature
