Repository monal-im/Monal, pull requests merged in 2021-03, with the labels that each got.

#588 Add missing items in the filetransfer cell.
  Monal/localization/Base.lproj/Main.storyboard
Labels: :art: UI

#586 Add hide keyboard function in Log page.
  Monal/Classes/LogViewController.h
  Monal/Classes/LogViewController.m
Labels: :art: UI, :no_entry_sign: Bug / Stability

#587 Fix large title cover chat content in Chat Logs.
  Monal/Classes/ChatLogAccountDetailViewController.m
  Monal/Classes/ChatLogContactViewController.m
  Monal/Classes/ChatLogsViewController.m
Labels: :art: UI, :iphone: iOS, :no_entry_sign: Bug / Stability

#589 Update MLServerDetails.m
  Monal/Classes/MLServerDetails.m
Labels: Minor
