Repository monal-im/Monal, pull requests merged in 2021-07, with the labels that each got.

#689 DOAP: Fix XML syntax (missing '>')
  monal.doap
Labels: :no_entry_sign: Bug / Stability, :superhero: Help wanted

#643 Add donations and support chat information
  ReadMe.md
Labels: Minor

#694 Create SECURITY.md
  SECURITY.md
Labels: :fire: Priority
